### ISSUE TITLE
doesn't build on 8.0.1

### ISSUE THREAD

**Issue by cartazio** [goldfirere/th-desugar#40] opened 2016-05-15 20:47 UTC
```
Language/Haskell/TH/Desugar/Reify.hs:186:24: error:
    Not in scope: data constructor ‘FamilyD’
    Perhaps you meant ‘FamilyI’ (imported from Language.Haskell.TH.Syntax)
cabal: Leaving directory '/var/folders/py/wgp_hj9d2rl3cx48yym_ynj00000gn/T/cabal-tmp-26278/th-desugar-1.5.5'
```

**Comment by christiaanb** [comment] 2016-05-16 07:32
I'm quite sure that the github version builds on GHC8. It's true that the version released on haddock doesn't.

**Comment by jstolarek** [comment] 2016-05-16 07:35
Duplicate of #39

**Comment by goldfirere** [comment] 2016-05-17 02:46
Released 1.6 today.

**Closed by goldfirere** 2016-05-17 02:46 UTC
